import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { PrintTripButton } from "@/components/print-trip-button";

function date(value:string|null){
  if(!value)return "TBC";
  return new Intl.DateTimeFormat("en-AU",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));
}
function dt(value:string|null){
  if(!value)return "TBC";
  return new Intl.DateTimeFormat("en-AU",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));
}

export default async function PrintTripPage({
  params,
  searchParams,
}:{
  params:Promise<{tripId:string}>,
  searchParams:Promise<{mode?:string}>
}){
  const {tripId}=await params;
  const {mode}=await searchParams;
  const simple=mode==="simple";
  const supabase=await createClient();
  const [
    {data:trip},{data:days},{data:activities},{data:bookings},{data:destinations},
    {data:members},{data:budgets},{data:expenses}
  ]=await Promise.all([
    supabase.from("trips").select("*").eq("id",tripId).maybeSingle(),
    supabase.from("itinerary_days").select("*").eq("trip_id",tripId).order("date"),
    supabase.from("activities").select("*").eq("trip_id",tripId).order("start_datetime"),
    supabase.from("bookings").select("*").eq("trip_id",tripId).order("start_datetime"),
    supabase.from("destinations").select("*").eq("trip_id",tripId).order("sort_order"),
    supabase.from("trip_members").select("user_id,role").eq("trip_id",tripId),
    supabase.from("budgets").select("planned_amount").eq("trip_id",tripId),
    supabase.from("expenses").select("converted_amount,amount").eq("trip_id",tripId),
  ]);
  if(!trip)notFound();

  const ids=(members??[]).map(m=>m.user_id);
  const {data:profiles}=ids.length?await supabase.from("profiles").select("id,display_name,first_name,last_name").in("id",ids):{data:[] as any[]};
  const names=(members??[]).map(m=>{const p=(profiles??[]).find(x=>x.id===m.user_id);return `${p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(" ")||"Traveller"} (${m.role})`;});
  const planned=(budgets??[]).reduce((s,b)=>s+Number(b.planned_amount||0),0);
  const spent=(expenses??[]).reduce((s,e)=>s+Number(e.converted_amount??e.amount??0),0);

  return <main className="print-trip">
    <div className="print-toolbar no-print">
      <PrintTripButton />
      <a href={`/trips/${tripId}/print`}>Full Trip Book</a>
      <a href={`/trips/${tripId}/print?mode=simple`}>Simple Itinerary</a>
      <a href={`/trips/${tripId}`}>Back to Trip</a>
    </div>
    <section className="print-cover" style={trip.cover_image_url?{backgroundImage:`linear-gradient(rgba(10,25,55,.48),rgba(10,25,55,.62)),url("${trip.cover_image_url}")`}:undefined}>
      <div><div className="eyebrow">Travel Crew Trip Book</div><h1>{trip.name}</h1><p>{trip.primary_destination}</p><strong>{date(trip.start_date)} – {date(trip.end_date)}</strong></div>
    </section>
    <section className="print-section"><h2>Trip Summary</h2><div className="print-info-grid">
      <div><span>Travellers</span><strong>{names.join(", ")||"TBC"}</strong></div>
      <div><span>Destinations</span><strong>{(destinations??[]).map(d=>d.name).join(" · ")||trip.primary_destination}</strong></div>
      <div><span>Budget</span><strong>${planned.toLocaleString("en-AU")} planned · ${spent.toLocaleString("en-AU")} spent</strong></div>
    </div></section>
    {!simple?<section className="print-section"><h2>Bookings</h2>{bookings?.length?<div className="print-list">{bookings.map(b=><article key={b.id}><strong>{b.booking_type.toUpperCase()} · {b.provider}</strong><span>{dt(b.start_datetime)}{b.end_datetime?` – ${dt(b.end_datetime)}`:""}</span>{b.booking_reference?<span>Reference: {b.booking_reference}</span>:null}</article>)}</div>:<p>No bookings saved.</p>}</section>:null}
    <section className="print-section"><h2>Day-by-Day Itinerary</h2>{days?.map(day=><article className="print-day" key={day.id}><h3>Day {day.day_number} · {date(day.date)}</h3>{(activities??[]).filter(a=>a.itinerary_day_id===day.id).length?<div className="print-list">{(activities??[]).filter(a=>a.itinerary_day_id===day.id).map(a=><div key={a.id}><strong>{a.start_datetime?new Intl.DateTimeFormat("en-AU",{hour:"numeric",minute:"2-digit"}).format(new Date(a.start_datetime)):""} {a.title}</strong><span>{[a.venue_name,a.address].filter(Boolean).join(" · ")}</span>{a.notes?<span>{a.notes}</span>:null}</div>)}</div>:<p>Free day / nothing planned.</p>}</article>)}</section>
    <footer className="print-footer">Generated by Travel Crew V2</footer>
  </main>;
}
