"use client";
import { useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Place={id:string;name:string;category:string;latitude:number;longitude:number;distance_km:number;address:string|null};

export function NearMe({tripId,userId}:{tripId?:string;userId?:string}){
 const supabase=useMemo(()=>createClient(),[]);const [location,setLocation]=useState<{lat:number;lon:number}|null>(null),[category,setCategory]=useState("restaurants"),[places,setPlaces]=useState<Place[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const cats=[["restaurants","Restaurants"],["cafes","Cafés"],["bars","Bars & Pubs"],["attractions","Attractions"],["landmarks","Landmarks"],["shopping","Shopping"],["pharmacies","Pharmacies"],["medical","Medical"],["hospitals","Hospitals"],["supermarkets","Supermarkets"],["convenience","Convenience"],["transport","Transport"],["parking","Parking"],["toilets","Toilets"],["fuel","Fuel"],["laundromats","Laundry"]];
 async function find(next=category){setCategory(next);setBusy(true);setMessage("");
  let loc=location;
  if(!loc){loc=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude}),()=>reject(new Error("Location permission is required.")),{enableHighAccuracy:true,timeout:10000})).catch(e=>{setMessage(e.message);return null}) as any}
  if(!loc){setBusy(false);return}setLocation(loc);
  try{const r=await fetch(`/api/near-me?lat=${loc.lat}&lon=${loc.lon}&category=${next}&radius=3000`);const p=await r.json();if(!r.ok)throw new Error(p.error||"Nearby search failed.");setPlaces(p.places??[]);if(!(p.places??[]).length)setMessage("No nearby results found.");}catch(e){setMessage(e instanceof Error?e.message:"Nearby search failed.")}finally{setBusy(false)}
 }
 async function save(place:Place){if(!tripId||!userId)return;const {error}=await supabase.from("saved_places").insert({trip_id:tripId,created_by:userId,name:place.name,category:place.category,address:place.address,latitude:place.latitude,longitude:place.longitude,notes:"Saved from Near Me"});setMessage(error?error.message:`${place.name} saved to this trip.`)}
 async function addToday(place:Place){if(!tripId||!userId)return;const today=new Date().toISOString().slice(0,10);let {data:day}=await supabase.from("itinerary_days").select("id").eq("trip_id",tripId).eq("date",today).maybeSingle();if(!day){const {data:created,error}=await supabase.from("itinerary_days").insert({trip_id:tripId,date:today,title:"Today"}).select("id").single();if(error){setMessage(error.message);return}day=created}const {error}=await supabase.from("activities").insert({trip_id:tripId,itinerary_day_id:day.id,created_by:userId,title:place.name,activity_type:place.category,venue_name:place.name,address:place.address,latitude:place.latitude,longitude:place.longitude,status:"planned"});setMessage(error?error.message:`${place.name} added to Today.`)}
 return <div className="near-me-stage7"><section className="panel"><div className="section-title-row"><div><h2>Near Me</h2><div className="muted">Uses your device location only when you choose to search.</div></div><button className="primary" onClick={()=>find()} disabled={busy}>{busy?"Searching…":"Use My Location"}</button></div><div className="explore-cats">{cats.map(([id,label])=><button key={id} className={category===id?"active":""} onClick={()=>find(id)}>{label}</button>)}</div>{message?<div className={message.includes("saved")||message.includes("added")?"success":"error"}>{message}</div>:null}</section><section className="near-me-grid">{places.map(p=><article className="explore-card" key={p.id}><div className="explore-pin">📍</div><h3>{p.name}</h3><div className="badge">{p.distance_km.toFixed(1)} km away</div>{p.address?<p className="muted">{p.address}</p>:null}<div className="inline-actions"><a className="text-link" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}#map=18/${p.latitude}/${p.longitude}`}>Map ↗</a>{tripId?<button onClick={()=>save(p)}>Save Place</button>:null}{tripId?<button onClick={()=>addToday(p)}>Add Today</button>:null}</div></article>)}</section></div>
}
