"use client";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Photo={id:string;storage_path:string;caption:string|null;taken_at:string|null;uploaded_at:string;uploaded_by:string;itinerary_day_id:string|null;is_favourite:boolean};
type Day={id:string;date:string;day_number:number|null};

export function TripPhotos({tripId,userId,initialPhotos,signedUrls,days=[]}:{tripId:string;userId:string;initialPhotos:Photo[];signedUrls:Record<string,string>;days?:Day[]}){
 const supabase=useMemo(()=>createClient(),[]);const [photos,setPhotos]=useState(initialPhotos),[urls,setUrls]=useState(signedUrls),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState<"all"|"favourites">("all");
 async function refresh(){const {data}=await supabase.from("photos").select("id,storage_path,caption,taken_at,uploaded_at,uploaded_by,itinerary_day_id,is_favourite").eq("trip_id",tripId).order("uploaded_at",{ascending:false});const next=data??[];setPhotos(next as Photo[]);const map:Record<string,string>={};for(const p of next){const r=await supabase.storage.from("trip-photos").createSignedUrl(p.storage_path,3600);if(r.data?.signedUrl)map[p.id]=r.data.signedUrl}setUrls(map)}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget;if(!file)return;setBusy(true);const f=new FormData(el);const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${tripId}/${userId}/${crypto.randomUUID()}-${safe}`;const u=await supabase.storage.from("trip-photos").upload(path,file,{contentType:file.type,upsert:false});if(u.error){setMessage(u.error.message);setBusy(false);return}const ins=await supabase.from("photos").insert({trip_id:tripId,uploaded_by:userId,storage_path:path,caption:String(f.get("caption")||"")||null,itinerary_day_id:String(f.get("day_id")||"")||null});if(ins.error){await supabase.storage.from("trip-photos").remove([path]);setMessage(ins.error.message)}else{el.reset();setFile(null);await refresh();setMessage("Photo added to timeline.");}setBusy(false)}
 async function favourite(p:Photo){const {error}=await supabase.from("photos").update({is_favourite:!p.is_favourite}).eq("id",p.id);if(error)setMessage(error.message);else await refresh()}
 async function del(p:Photo){if(!confirm("Delete this photo?"))return;const r=await supabase.from("photos").delete().eq("id",p.id);if(r.error){setMessage(r.error.message);return}await supabase.storage.from("trip-photos").remove([p.storage_path]);await refresh()}
 const shown=filter==="favourites"?photos.filter(p=>p.is_favourite):photos;
 const groupDate=(p:Photo)=>days.find(d=>d.id===p.itinerary_day_id)?.date||p.taken_at?.slice(0,10)||p.uploaded_at.slice(0,10);
 const groups=Array.from(new Set(shown.map(groupDate)));
 return <div className="photo-stage6"><form className="panel form-stack" onSubmit={upload}><div className="section-title-row"><div><h2>Photo Timeline</h2><div className="muted">Attach photos to trip days and mark favourites.</div></div><div className="view-switch"><button type="button" className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All</button><button type="button" className={filter==="favourites"?"active":""} onClick={()=>setFilter("favourites")}>★ Favourites</button></div></div><div className="form-grid"><div className="field"><label>Photo *</label><input type="file" accept="image/*" required onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]??null)}/></div><div className="field"><label>Trip day</label><select name="day_id"><option value="">Unassigned</option>{days.map(d=><option key={d.id} value={d.id}>Day {d.day_number} · {d.date}</option>)}</select></div><div className="field span-2"><label>Caption</label><input name="caption"/></div></div><button className="primary" disabled={!file||busy}>{busy?"Uploading…":"Add Photo"}</button></form>
 {groups.map(date=><section className="photo-day-group" key={date}><h3>{date}</h3><div className="photo-gallery">{shown.filter(p=>groupDate(p)===date).map(p=><article className="photo-tile" key={p.id}>{urls[p.id]?<img src={urls[p.id]} alt={p.caption||"Trip photo"}/>:<div className="photo-placeholder">📸</div>}<div className="photo-tile-body"><div><strong>{p.caption||"Trip photo"}</strong></div><div className="photo-buttons"><button type="button" onClick={()=>favourite(p)}>{p.is_favourite?"★":"☆"}</button>{p.uploaded_by===userId?<button className="icon-danger" type="button" onClick={()=>del(p)}>×</button>:null}</div></div></article>)}</div></section>)}
 {!shown.length?<div className="empty-state"><h3>No photos in this view</h3></div>:null}{message?<div className={message.includes("added")?"success":"error"}>{message}</div>:null}</div>
}
