import { redirect } from "next/navigation";import { requireUser,getCurrentRole } from "@/lib/auth";import { createClient } from "@/lib/supabase/server";
export default async function HealthPage(){const user=await requireUser();const role=await getCurrentRole(user.id);if(role!=="owner")redirect("/dashboard");const supabase=await createClient();const checks:any[]=[];
 const q=await supabase.from("trips").select("id",{head:true,count:"exact"});checks.push({name:"Supabase database connection",ok:!q.error,detail:q.error?.message||"Connected"});
 const p=await supabase.from("push_subscriptions").select("id",{head:true,count:"exact"});checks.push({name:"Stage 7/8 push table",ok:!p.error,detail:p.error?.message||"Available"});
 const d=await supabase.from("documents").select("alert_days",{head:true,count:"exact"});checks.push({name:"Stage 8 database migration",ok:!d.error,detail:d.error?.message||"Stage 8 fields available"});
 checks.push({name:"Supabase URL",ok:Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL),detail:process.env.NEXT_PUBLIC_SUPABASE_URL?"Configured":"Missing"});
 checks.push({name:"Supabase public key",ok:Boolean(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY),detail:process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?"Configured":"Missing"});
 checks.push({name:"Pexels images",ok:Boolean(process.env.PEXELS_API_KEY),detail:process.env.PEXELS_API_KEY?"Configured":"Optional key missing"});
 checks.push({name:"Web Push public key",ok:Boolean(process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY),detail:process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY?"Configured":"Push not configured"});
 checks.push({name:"Web Push private key",ok:Boolean(process.env.VAPID_PRIVATE_KEY),detail:process.env.VAPID_PRIVATE_KEY?"Configured":"Push not configured"});
 checks.push({name:"VAPID subject",ok:Boolean(process.env.VAPID_SUBJECT),detail:process.env.VAPID_SUBJECT?"Configured":"Push not configured"});
 checks.push({name:"Paid AI API",ok:Boolean(process.env.OPENAI_API_KEY),detail:process.env.OPENAI_API_KEY?"Configured":"Optional — Free Smart Planner remains available"});
 const passed=checks.filter(c=>c.ok).length;return <><header className="page-header"><div><h1>Production Readiness</h1><div className="muted">Owner-only health check. No secret values are displayed.</div></div><span className="badge">{passed}/{checks.length} checks</span></header><section className="panel health-stage8">{checks.map(c=><article className={c.ok?"pass":"warn"} key={c.name}><span>{c.ok?"✓":"!"}</span><div><strong>{c.name}</strong><small>{c.detail}</small></div></article>)}</section><section className="panel"><h2>Final travel test checklist</h2><div className="audit-checks"><label>□ Test iPhone/Safari PWA install and push</label><label>□ Test Android/Chrome PWA install and push</label><label>□ Test invitations with a non-owner account</label><label>□ Test offline checklist, packing, journal and Quick Add</label><label>□ Download a full trip backup</label><label>□ Confirm passports/insurance are visible only to trip members</label><label>□ Test timezones across Sydney and overseas destinations</label><label>□ Test expenses and settlement calculations</label></div></section></>}
